### ISSUE TITLE
todo: move medicine notebook to epark

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#120]
- [x] sign up epark
- [x] take picture to epark old
- [x] take picture to epark now
