### ISSUE TITLE
todo: set jre id and moneyforward

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#122]
- [ ] https://www.jreast.co.jp/myjreast/
- [ ] unify view card
- [ ] unify mobile suica
- [ ] unify jre point
- [ ] set moneyforward suica: delete+insert
