### ISSUE TITLE
todo: sell by paypay or merkari or jimoty

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#129]
- [x] Dehumidifier by paypay free market
- [x] humidifier by paypay free market
- [x] cleaner: should set new pack
- [x] rice cooker
- [x] printer canon: should buy ink black, should reset Dropbox
- [ ] display iodata
- [x] kindle paperwhite: should reset
- [x] kindle fire hd8: should reset
- [ ] hdd 2 TB: should reset
- [ ] hdd 128 GB: should reset
- [ ] usb 8 GB: should reset
- [ ] usb 256MB: should reset
- [ ] router

dispose small household appliance by paypay-free at 1215 (sun) or mercari or jimoty or hinoshi-free-collection next 1225 wed monthly
