### ISSUE TITLE
todo: contract ymobile share ixs, p3-sub, tablet

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#145]
- [ ] unlock sim, docomo
- [ ] disable docomo, investigate effect
- [ ] contract ymobile sim max 3, with iPhone8
