### ISSUE TITLE
todo: buy microwave

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#147]
- [x] simple or oven - oven
- [x] go yodo? - Yamada
- [x] paypay or yodo - Yamada
