### ISSUE TITLE
todo: move itomakiweb to hidecharo

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#151]
- [x] google is id (import music fastly)
- [x] github is id
- [x] amazon is mail
- [x] twitter is id
- [x] slack is mail and id (enable change)
- [x] discord is mail and id (enable change)
- [x] facebook is id
- [x] instagram is id
- [x] qiita is id
- [x] note is id
- [x] freee is mail add account
- [x] dropbox is unknown but not move
- sakura is disable #137
- xrea is disable #138
- value domain is disable #139
- [x] apple is mail https://www.au.com/support/faq/view.k1202140012/ https://time-space.kddi.com/digicul-column/digicul-joho/20180313/2265
  - [x] mbp: logout appstore, preference
  - [x] ixs: logout preference (find my,  appstore, unnecesary: health wallet)
  - [x] mbp: login app store change nickname
  - [x] ixs: login
- [ ] yodobashi is mail
- [ ] oreilly is mail
- [ ] honto is mail? already hidecharo?
- [ ] psn is mail and id (enable change)
- [ ] hankoya is id?
- [ ] starts pitat yumenavi is id?
- [ ] ieshil is id?
- [ ] premium water is id?
- [ ] kuroneko is id?
- [ ] yubin is id?
- [ ] sokuhai is id?
- [ ] suido is id?
- [ ] surugaya is id?
- [ ] nico is id?
- [ ] card-amazon is id?
- [ ] card-yodobashi is id?
- [ ] card-view is id?
- [ ] sumishin-net is id?
- [ ] japan-net is id?
- [ ] mizuho is id?
- [x] paypal is mail
- [ ] mineo is id?
- [ ] EPARK is id?
- [ ] visasq is id?
- [ ] ochatomo is id? already hidecharo?
- [ ] rurubu is id?
- [ ] ekinet is id?
- [ ] jetbrains is id?
- [ ] adsense is id?
- [ ] google search console is id?
- [ ] anytime fitness is id? already hidecharo?
- [ ] dqwalk: sqid
- [ ] pokemon go, google account
- [ ] minecraft: xbox account, microsoft account (hotmail outlook)
- [ ] paypay is id
- [ ] yahoo is id
- [ ] on p3
  - [ ] (use paypay bonuses)
  - [ ] change 080 to 090 on paypay
  - [ ] check ymobile status
  - [ ] wait 1~ week
  - [ ] logout and cache clear and uninstall and install
  - [ ] register 080 no yj
  - [ ] register id hidecharo
- [ ] on ixs
  - [ ] docomo is id and enable change
  - [ ] change docomo to ymobile shareplan
- [ ] on p3
  - [ ] change 080 to 090 on yj
  - [ ] unset ymobile itomakiweb
  - [ ] set ymobile hidecharo
  - [ ] set yj on paypay
  - [ ] register ymobile on paypay
  - [ ] finally bank is blank
- [ ] yahoo-corp registerd mail (emergency alert)
- [ ] confirm account if account is mail address, then change address, else account has id, then register new account, Hide Charo (ひで)
- [ ] move all account
- [ ] use itomakiweb for corp
