### ISSUE TITLE
todo: prepare nuro hikari

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#156]
- [x] tell permit mansion admin
- [ ] wait permit mansion admin
- [ ] tell nuro hikari schedule, and confirm price 980, cash back.
- [ ] confirm mail
- [ ] install app, register
