### ISSUE TITLE
todo: contract amazon associate

### ISSUE THREAD

**Issue by itomakiweb** [hidecharo/next#170]
- [ ] change itomakiweb to hidecharo amazon account
- [ ] contract amazon association
- [ ] new itomakiweb tracking hidecharo or use hide_webmaster
